CREATE TABLE IF NOT EXISTS options
(
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id UUID NOT NULL REFERENCES questions (id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL     DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL     DEFAULT CURRENT_TIMESTAMP
);